Update 01-building-blocks.yaml

diff --git a/01-building-blocks.yaml b/01-building-blocks.yaml
--- a/01-building-blocks.yaml
+++ b/01-building-blocks.yaml
@@ -1,15 +1,19 @@
 name: 01 - Building Blocks
-on: push, workflow_dispatch
+
+on: push
 
 jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
-      - run: echo "Hello,World!"
+      - name: Say Hello
+        run: echo "Hello,World!"
   second-job:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
-        run: "I will fail"
+        run: |
+              echo "I will fail"
+              exit 1
       - name: Say goodbye
-        run: "Goodbye" 
+        run: echo "Goodbye" 
